USE [etriline]
GO

/****** Object:  Table [TRILINE\dmitry].[TENDER]    Script Date: 03/24/2015 17:42:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [TRILINE\dmitry].[TENDER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER] [varchar](500) NULL,
	[CITY] [varchar](50) NULL,
	[ADDRESS] [varchar](2000) NULL,
	[URL] [varchar](500) NULL,
	[DATE_START] [varchar](8) NULL,
	[DATE_DOCS] [varchar](12) NULL,
	[DATE_DOCS_MSK] [int] NULL,
	[DATE_ACT] [varchar](12) NULL,
	[DATE_ACT_MSK] [int] NULL,
	[THEME] [varchar](250) NULL,
	[SUM_START] [int] NULL,
	[SUM_TRL] [int] NULL,
	[SUM_WIN] [int] NULL,
	[TIP] [int] NULL,
	[MANAGER] [int] NULL,
	[RESULT] [int] NULL,
	[WINNER] [varchar](100) NULL,
	[TXT] [varchar](2000) NULL,
	[SUM_ZERO] [int] NULL,
	[CHECK_NUM] [varchar](50) NULL,
	[DATE_ADD] [varchar](8) NULL,
	[DATE_USE] [varchar](12) NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [TRILINE\dmitry].[TENDER] ADD  CONSTRAINT [DF_TENDER_DATE_DOCS_MSK]  DEFAULT ((0)) FOR [DATE_DOCS_MSK]
GO

ALTER TABLE [TRILINE\dmitry].[TENDER] ADD  CONSTRAINT [DF_TENDER_DATE_ACT_MSK]  DEFAULT ((0)) FOR [DATE_ACT_MSK]
GO

ALTER TABLE [TRILINE\dmitry].[TENDER] ADD  CONSTRAINT [DF_TENDER_SUM_ZERO]  DEFAULT ((0)) FOR [SUM_ZERO]
GO

ALTER TABLE [TRILINE\dmitry].[TENDER] ADD  CONSTRAINT [DF_TENDER_DATE_USE]  DEFAULT ('') FOR [DATE_USE]
GO


