USE [etriline]
GO

/****** Object:  Table [TRILINE\dmitry].[TENDER_LOG]    Script Date: 03/25/2015 13:50:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [TRILINE\dmitry].[TENDER_LOG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MANAG] [int] NOT NULL,
	[TXT] [text] NOT NULL,
	[TENDER] [int] NOT NULL,
	[DAT] [varchar](50) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [TRILINE\dmitry].[TENDER_LOG] ADD  CONSTRAINT [DF_TENDER_LOG_MANAG]  DEFAULT ((0)) FOR [MANAG]
GO

ALTER TABLE [TRILINE\dmitry].[TENDER_LOG] ADD  CONSTRAINT [DF_TENDER_LOG_TENDER]  DEFAULT ((0)) FOR [TENDER]
GO

ALTER TABLE [TRILINE\dmitry].[TENDER_LOG] ADD  CONSTRAINT [DF_TENDER_LOG_DAT]  DEFAULT ('') FOR [DAT]
GO

