USE [etriline]
GO

/****** Object:  Table [TRILINE\dmitry].[TENDER_USER]    Script Date: 03/25/2015 13:51:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [TRILINE\dmitry].[TENDER_USER](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LOGIN] [varchar](50) NULL,
	[PASS] [char](32) NULL,
	[FIO] [varchar](150) NULL,
	[TIP] [int] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [TRILINE\dmitry].[TENDER_USER] ADD  CONSTRAINT [DF_TENDER_USER_TIP]  DEFAULT ((0)) FOR [TIP]
GO

